### ISSUE TITLE
Toggling Navigation Bar's visibility

### ISSUE THREAD

**Issue by danieldocki** [lazaronixon/react-native-turbolinks#1]
I would like to display the navigation bar in some pages and others not, is it possible?

**Comment by lazaronixon** [comment]
Not yet.. I have plans to add params on visit method to hide navigationbar, display right button.. linkable subtitle etc... I am working on android for while.

**Comment by danieldocki** [comment]
Ohh amazing... thanks for the great work.

**Comment by lazaronixon** [comment]
now you can use 'modal' param on visit.. I am working on navbar and I am planning to set visibility only once for all views too.. its ok for you case?

**Comment by danieldocki** [comment]
oh yeah, looking forward to testing.

Thanks.

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.1.0

**Comment by danieldocki** [comment]
When I run the example I get the error:

```
Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `processColor` from `/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/react-native-turbolinks/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1719)
    at ResolutionRequest.resolveDependency (/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at Promise (<anonymous>)
    at /Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/Users/danieldocki/Projects/ReactNative/react-native-turbolinks/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/15), failed.
```

**Comment by lazaronixon** [comment]
Solved to me reboot computer..

**Comment by danieldocki** [comment]
unsuccessful after restarting the computer...

I think this line is the problem https://github.com/lazaronixon/react-native-turbolinks/blob/master/index.js#L7

**Comment by lazaronixon** [comment]
Thank you.. Fixed.. 2afe2aa720009a01f563d94a4b92bb7500bb62a4

**Comment by danieldocki** [comment]
Great Job @lazaronixon.

I'm tested `setNavigationBarHidden` and is working perfect. I'll test more and give you a feeback.

Thank You!
